### ISSUE TITLE
Front end for ECSAS?

### ISSUE THREAD

**Issue by grwhumphries** [RoyChristian/ECSASconnect#10]
Sorry, Not sure how to best connect with you folks so feel free to close this issue when you've looked. Just wanted to know if ECSAS has a front-end solution for connecting to the database. I can't seem to find it (if existing).  Any intention of making one?

**Comment by RoyChristian** [comment]
Hi Gant, the ECSAS database is a rather large database so it's not possible to host in on Github. At some point the database should be available through the Canadian Wildlife Service open data portal but this application is still in development. In the meantime, you will need to contact either François (francois.bolduc@canada.ca) or Dave (dave.fifield@canada.ca) and sign a data-sharing agreement to get a copy of the database. Hope this help!
Chris
